# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb1e8d3afa341f0738ecb5ed186c3f72365a7e38a6c9cc7a619f6fdb3ae4e7837fab354ac9408b7e30a15bb3578517560174c60c97fd436345f9cad6c099243f

test:
  secret_key_base: 36c723639c7e95441719a22e54920fc71a06001be8f80396cefd0e775640a22cfb3fb3b8b0fd5c96325a99b9be9238e9d09c1e719d9527a5f212e5692ab9ef5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
